name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost=1.74.0=py37h796e4cb_4
  - boost-cpp=1.74.0=hc6e9bd1_3
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py37h89c1867_1
  - cffi=1.14.5=py37hc58025e_0
  - chardet=4.0.0=py37h89c1867_1
  - conda=4.9.2=py37h89c1867_0
  - conda-package-handling=1.7.2=py37hb5d75c8_0
  - cryptography=3.4.5=py37h5d9358c_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.11.0=h70c0345_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h516909a_2
  - greenlet=1.1.2=py37hcd2ae1e_1
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.8.2=py37h89c1867_0
  - jpeg=9d=h516909a_0
  - kiwisolver=1.3.2=py37h2527ec5_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libarchive=3.5.1=h3f442fb_1
  - libblas=3.9.0=12_linux64_openblas
  - libcblas=3.9.0=12_linux64_openblas
  - libcurl=7.75.0=hc4aaa36_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=hed695b0_2
  - libsolv=0.7.17=h780b84a_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=h72842e0_3
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - mamba=0.8.0=py37h7f483ca_0
  - matplotlib-base=3.4.3=py37h1058ff1_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.21.4=py37h31617e3_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1l=h7f98852_0
  - pandas=1.3.4=py37he8f5f7f_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pycairo=1.20.1=py37hfff247e_1
  - pycosat=0.6.3=py37h5e8e339_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.10=hffdb5ce_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.3=pyhd8ed1ab_0
  - rdkit=2021.09.2=py37h13c2175_0
  - readline=8.0=he28a2e2_2
  - reportlab=3.5.68=py37h69800bb_0
  - reproc=14.2.1=h36c2ea0_0
  - reproc-cpp=14.2.1=h58526e2_0
  - requests=2.25.1=pyhd3deb0d_0
  - ruamel_yaml=0.15.80=py37h5e8e339_1004
  - setuptools=49.6.0=py37h89c1867_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlalchemy=1.4.27=py37h5e8e339_0
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py37h5e8e339_2
  - tqdm=4.59.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - altair==4.1.0
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - astor==0.8.1
    - attrs==21.2.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==4.2.4
    - click==7.1.2
    - condacolab==0.1.3
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - gitdb==4.0.9
    - gitpython==3.1.24
    - importlib-resources==5.4.0
    - ipykernel==6.5.0
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.2.1
    - jupyter-client==7.0.6
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.8
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - packaging==21.2
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plotly==4.4.1
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - ptyprocess==0.7.0
    - pyarrow==6.0.0
    - pydeck==0.7.1
    - pygments==2.10.0
    - pympler==0.9
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==22.3.0
    - retrying==1.3.3
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - send2trash==1.8.0
    - smmap==5.0.0
    - streamlit==1.2.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - toolz==0.11.2
    - traitlets==5.1.1
    - tzdata==2021.5
    - tzlocal==4.1
    - validators==0.18.2
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
prefix: /usr/local
